name: Build TDLib for CoreELEC (Standalone)

on:
  workflow_dispatch:  # This allows you to manually trigger the job

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            make \
            git \
            gperf \
            php-cli \
            ninja-build \
            musl-tools \
            g++-aarch64-linux-gnu

      - name: Build zlib (Static)
        run: |
          wget https://zlib.net/zlib-1.3.1.tar.gz
          tar -xzvf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          CC=aarch64-linux-gnu-gcc ./configure --static --prefix=$HOME/static-libs
          make
          make install
          
      - name: Build OpenSSL (Static for ARM64)
        run: |
          # Download OpenSSL source
          wget https://www.openssl.org/source/openssl-1.1.1m.tar.gz
          tar -xzvf openssl-1.1.1m.tar.gz
          cd openssl-1.1.1m

          # Clean up any old build artifacts
          rm -rf $HOME/static-libs/openssl

          # Configure OpenSSL for ARM64 explicitly
          # This command assumes you want OpenSSL to be statically compiled for ARM64
          ./config --prefix=$HOME/static-libs/openssl --openssldir=$HOME/static-libs/openssl/ssl no-shared

          # Compile OpenSSL
          make -j$(nproc)

          # Install OpenSSL
          make install

          # Optionally: create symlinks to make OpenSSL the default on the system
          sudo ln -s $HOME/static-libs/openssl/bin/openssl /usr/bin/openssl
          sudo ln -s $HOME/static-libs/openssl/bin/c_rehash /usr/bin/c_rehash







      - name: Build TDLib (Static with musl)
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=../tdlib \
                -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                -DCMAKE_FIND_ROOT_PATH=$HOME/static-libs \
                -DOPENSSL_ROOT_DIR=$HOME/static-libs/openssl \
                -DZLIB_ROOT=$HOME/static-libs \
                -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
                ..
          cmake --build . --target install -- -j$(nproc)

      - name: Package TDLib
        run: |
          cd td/tdlib
          tar -czvf tdlib-coreelec-standalone.tar.gz *

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tdlib-coreelec-standalone
          path: td/tdlib/tdlib-coreelec-standalone.tar.gz
