name: Build TDLib for CoreELEC (Standalone)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            make \
            git \
            gperf \
            php-cli \
            ninja-build \
            musl-tools \
            g++-aarch64-linux-gnu

      - name: Build zlib (Static)
        run: |
          wget http://zlib.net/zlib-1.2.11.tar.gz
          tar -xzvf zlib-1.2.11.tar.gz
          cd zlib-1.2.11
          CC=aarch64-linux-gnu-gcc ./configure --static
          make
          make install PREFIX=$HOME/static-libs/zlib

      - name: Build OpenSSL (Static)
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1.tar.gz
          tar -xzvf openssl-1.1.1.tar.gz
          cd openssl-1.1.1
          ./Configure linux-aarch64 no-shared --prefix=$HOME/static-libs/openssl
          make
          make install

      - name: Build TDLib (Static with musl)
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=../tdlib \
                -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                -DCMAKE_FIND_ROOT_PATH=$HOME/static-libs \
                -DOPENSSL_ROOT_DIR=$HOME/static-libs/openssl \
                -DZLIB_ROOT=$HOME/static-libs/zlib \
                -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
                ..
          cmake --build . --target install -- -j$(nproc)

      - name: Package TDLib
        run: |
          cd td/tdlib
          tar -czvf tdlib-coreelec-standalone.tar.gz *
        # Save the build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tdlib-coreelec-standalone
          path: td/tdlib/tdlib-coreelec-standalone.tar.gz
